### ISSUE TITLE
编译原理-学习笔记 - Zhang T's Blog

### ISSUE THREAD

**Issue by zhangt2333** [zhangt2333/zhangt2333.github.io#11]
https://zhangt.top/CS/Compilation-Principles-Study-Notes/

**Comment by chen2438** [comment]
https://zhangt.top/CS/Compilation-Principles-Study-Notes/#%E6%9E%84%E9%80%A0-FIRST-%CE%B1

这里的 Latex 没有被渲染出来，是我的问题吗？可以修正吗？

![image](https://github.com/zhangt2333/zhangt2333.github.io/assets/53367039/22c32737-6012-4312-9d2f-ce3ee79dc82f)

**Comment by zhangt2333** [comment]
@chen2438 

这个 Hexo 博客的配置有点老了，它对数学公式的支持不是很 robust，更别说我平时用 Typora 写的 LaTeX 很复杂导致在它这渲染不起来。

我没有时间去修复它，可能下一步是选用一个新的博客，但那是未来的事情了。

如果你对某博客感兴趣，可以告诉我，我会给你它的 PDF 版。

**Comment by chen2438** [comment]
我在学习国科大的PPT，不需要PDF版了。还是感谢您。
